name: model-training

on:
  push:
    branches: ["dev-manh"]
  pull_request:
    branches: ["main"]

jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3

      - name: Set up
        uses: iterative/setup-tools@v1

      - name: Train model
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_TABLE: ${{ secrets.SNOWFLAKE_TABLE }}

        run: |
          # Cài đặt các thư viện cần thiết
          pip install -r requirements.txt
          pip install snowflake-connector-python
          
          # Thực thi pipeline
          dvc repro

          # Đẩy kết quả (outputs) lên remote storage (nếu dùng DVC remote)
          dvc push

      - name: Push DVC outputs
        if: always()
        run: dvc push

      - name: Report metrics with CML
        run: |
          cml-send-comment metrics.json --md report.md --fail-on error
